# Generated by Django 2.1.5 on 2019-01-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=243)),
                ('answer', models.CharField(max_length=243)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
